### ISSUE TITLE
Request: CharacterEdit to work with Ben's Mod Loader

### ISSUE THREAD

**Issue by jinglyjangles** [aedenthorn/GoingMedievalMods#1]
https://github.com/benjaminfoo/GoingMedievalModLauncher

Looks like both BepInEx and Ben's mod loader are using the same dll's. Wondering if you can 'port' your mod over to his loader?

**Comment by aedenthorn** [comment]
no, BepInEx is the standard, there is no reason I can see to use a custom homemade mod loader.
